django_app/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('university.urls', namespace='universities'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

university/urls.py
from django.urls import path
from .views import *

app_name = 'university'

urlpatterns = [
    path('', UniversityViews.as_view(), name='universities'),
    path('new/<int:pk>', UniversityDetail.as_view(), name='detail-page'),
    path('update/<int:pk>', UpdateNews.as_view(), name='update'),
    path('delete/<int:pk>', DeleteNews.as_view(), name='delete'),
    path('create/', AddViews.as_view(), name='add-page'),
    path('universities/', Universities.as_view(), name='list-universities'),
    path('mit/', Mit.as_view(), name='mit'),
    path('columbia/', Columbia.as_view(), name='columbia'),
    path('harvard/', Harvard.as_view(), name='harvard'),
    path('stanford/', Stanford.as_view(), name='stanford'),
    path('news/', AllNews.as_view(), name='news-list'),
    path('home/', HomeViews.as_view(), name='home'),
    path('education/', EducationViews.as_view(), name='education')
]

university/models.py
from django.db import models
from django.urls import reverse
from uuid import uuid4
from django.db.models.signals import pre_save


def upload_location(instance, filename):
    ext = filename.split('.')[-1]
    # file_path = "news_archive/{filename}".format(
    #     filename='{}.{}'.format(uuid4().hex, ext))
    file_path = f"news_archive/{uuid4().hex}.{ext}"
    return file_path


class FamousUniversitie(models.Model):
    name = models.CharField(max_length=100)
    about = models.TextField()
    country = models.CharField(max_length=100)
    author = models.ForeignKey('auth.user', on_delete=models.CASCADE)
    image = models.ImageField(upload_to=upload_location, null=True, blank=True)

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse("university:detail-page", args=[str(self.id)])

    @property
    def imageUrl(self):
        try:
            url = str(self.image.url)
        except:
            url = ''
        return url

university/views.py
from django.shortcuts import render
from django.views.generic import ListView, TemplateView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import *

class UniversityViews(ListView):
    model = FamousUniversitie
    template_name = 'news.html'

class AllNews(ListView):
    model = FamousUniversitie
    template_name = 'all_news.html'
    context_object_name = 'news_list'

class UpdateNews(UpdateView):
    model = FamousUniversitie
    template_name = 'update_news.html'
    fields = ['name', 'image', 'about', 'country']

class DeleteNews(DeleteView):
    model = FamousUniversitie
    template_name = 'delete_news.html'
    success_url = reverse_lazy('university:')
    context_object_name = 'new'


class UniversityDetail(DetailView):
    model = FamousUniversitie
    template_name = "detail-page.html"
    context_object_name = 'news'

class AddViews(CreateView):
    model = FamousUniversitie
    template_name = 'add-news.html'
    fields = ['name', 'image', 'about', 'country', 'author']

class Universities(TemplateView):
    template_name = 'main/universities.html'

class Mit(TemplateView):
    template_name = 'main/mit.html'

class Columbia(TemplateView):
    template_name = 'main/columbia.html'

class Harvard(TemplateView):
    template_name = 'main/harvard.html'

class Stanford(TemplateView):
    template_name = 'main/stanford.html'

class HomeViews(ListView):
    model = FamousUniversitie
    template_name = 'news.html'

class EducationViews(TemplateView):
    template_name = 'main/education.html'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Universities - The best of the world!</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="Bootstrap Ecommerce Template" name="keywords">
        <meta content="Bootstrap Ecommerce Template Free Download" name="description">

        <!-- Favicon -->
        <link href="img/favicon.ico" rel="icon">

        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700&display=swap" rel="stylesheet">

        <!-- CSS Libraries -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="{% static 'lib/slick/slick.css' %}" rel="stylesheet">
        <link href="{% static 'lib/slick/slick-theme.css' %}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    </head>

    <body>
    {% include 'snippets/header.html' %}
        {% block content %}

        {% endblock %}
    {% include 'snippets/footer.html' %}
    </body>

templates/main/columbia.html
{% extends 'base.html' %}
{% load static %}
{% include 'snippets/header.html' %}

{% block content %}
<h1>Columbia University</h1>
<p><h3>Columbia University is one of the most prestigious and authoritative universities in the USA, founded in 1754 (the fifth oldest institution of higher education in the USA) with the support of King George II of Great Britain. It has 33,000 students, most of them undergraduate and graduate students.
    The main campus of Columbia University is located in Manhattan on the territory of 6 blocks of New York, many of the university's buildings are listed on the US National Register of Historic Places. Columbia owns 25 libraries.
    The university is a member of the Ivy League, is one of the founding universities of the prestigious Association of American Universities. Columbia University is a doctoral university with a very high scientific activity. Within the walls of Columbia University, many scientific and technical discoveries were made, including the fission of uranium and the working prototype of a laser. Past and current faculty at the university include 30 MacArthur Award winners, 43 National Academy of Sciences award winners, 143 American Academy of Arts and Sciences award winners, and other prestigious award winners. The Pulitzer Prize is awarded by the university's journalism department.
    Alumni include five US Founding Fathers, three US Presidents (Barack Obama, Franklin Delano Roosevelt, and Theodore Roosevelt), over 100 Pulitzer Prize winners, and over 40 Oscar winners. 84 Nobel laureates have studied or taught at Columbia.</h3></p>
<img src="{% static 'img/columbia1.jpg' %}" alt="mit">
<h2>Why go to the Columbia University?</h2>
<p><h3>- a unique chance to get a diploma from one of the most famous universities in the world;</h3></p>
<p><h3>- dozens of student organizations operate at the university, it even has its own radio station, two newspapers, a magazine and a television studio;</h3></p>
<p><h3>- 95% of graduates find a job within six months after graduation, the university ranks 21st in the world ranking of graduate employability (according to QS - Quacquarelli Symonds).</h3></p>


<h2>Strong directions:</h2>
<p><h4>- journalism and media communications</h4></p>
<p><h4>- humanities and social sciences (global studies, history, philosophy, sociology, psychology, political science and economics)</h4></p>
<p><h4>- cinema, theater and dance</h4></p>
<p><h4>- engineering and computer science</h4></p>
<p><h4>- architecture</h4></p>
<p><h4>- physics and mathematics</h4></p>

{% endblock %}

{% include 'snippets/footer.html' %}

templates/main/harvard.html
{% extends 'base.html' %}
{% load static %}
{% include 'snippets/header.html' %}

{% block content %}
<h1>Harvard University</h1>
<p><h3>Harvard University is the oldest university in the United States, founded in 1636 and named after the priest John Harvard, who left half of his property and an extensive library to the university. At the moment, 21,000 students study at the university, with the majority being graduate and doctoral students.
    Harvard boasts a huge campus of more than 2000 hectares, equipped with the latest technology. The campus infrastructure includes world-class scientific laboratories, sports centers, several museums, libraries, cafes, and clubs. The University Library is the largest academic library in the world with 18 million books.
    Harvard University is one of the most prestigious universities in the world, a member of the elite Ivy League and the prestigious Association of American Universities. The university's annual research spending is more than $1.1 billion - according to this indicator, the university ranks 9th among US universities. More than 50 Nobel laureates are associated with the name of the university (teachers, alumni, researchers).
    Harvard University alumni include 8 American presidents, 188 living billionaires, 108 Olympic medalists, and 10 Oscar winners.</h3></p>
<img src="{% static 'img/harvard1.jpg' %}" alt="harvard">
<h2>Why go to the Harvard University?</h2>
<p><h3>- a unique chance to get a diploma from one of the most famous universities in the world;</h3></p>
<p><h3>- rich extracurricular life - over 400 student organizations (including creative and professional communities) and 42 sports clubs;</h3></p>
<p><h3>- 5th place in the world ranking of graduate employability (according to QS - Quacquarelli Symonds).</h3></p>


<h2>Strong directions:</h2>
<p><h4>- humanitarian and social disciplines (psychology, philosophy, political science, history, sociology, etc.)</h4></p>
<p><h4>- medicine and healthcare</h4></p>
<p><h4>- jurisprudence</h4></p>
<p><h4>- business and economics</h4></p>
<p><h4>- art</h4></p>
<p><h4>- engineering and computer science</h4></p>

{% endblock %}

{% include 'snippets/footer.html' %}

templates/main/mit.html
{% extends 'base.html' %}
{% load static %}
{% include 'snippets/header.html' %}

{% block content %}
<h1>MIT University</h1>
<p><h3>The Massachusetts Institute of Technology (MIT) is a US private research university founded in 1861 in response to the country's rapid industrial development. The university has almost 12,000 students from 115 countries. The MIT campus is located 3 miles from downtown Boston. It is built in a modern urban style with colorful garden areas and is convenient for cycling and walking. The campus houses laboratories for a wide range of scientific disciplines, as well as an educational working nuclear reactor and an artificial intelligence research center.
    The Massachusetts Institute of Technology is considered a doctoral university with a very high scientific activity, according to the Carnegie classification of institutions of higher education. Every year, the university spends about $1 billion on research - according to this indicator, it ranks 14th in the United States. MIT is one of the first universities to collaborate with other universities, business, and the government on research. For example, the university actively cooperates with Harvard in the field of medicine and technology (largely due to the geographical proximity of the campuses). MIT students can take courses from Harvard University, and vice versa.
    The name of the university is associated with 97 Nobel laureates (40 of them are alumni), 26 Turing Prize winners, 8 Fields Medalists, 50 MacArthur Scholars and 80 Marshall Scholars. Also, former UN Secretary General Kofi Annan, Israeli Prime Minister Benjamin Netanyahu, Intel founder Robert Noyce and others studied at the university.</h3></p>
<img src="{% static 'img/mit.jpeg' %}" alt="mit">
<h2>Why go to the Massachusetts Institute of Technology?</h2>
<p><h3>- there are more than 500 student organizations and groups at the university - you can join any or create your own; university sports teams play in professional student leagues in 33 sports;</h3></p>
<p><h3>unique employment opportunities - the university takes 1st place in the world ranking of graduate employability (according to QS - Quacquarelli Symonds). Students do internships during their studies, and graduates work at Google, Oracle, Amazon, McKinsey Accenture, Apple, Boeing and Microsoft in high positions.</h3></p>

<h2>Strong directions:</h2>
<p><h4>- engineering</h4></p>
<p><h4>- computer science and information technology</h4></p>
<p><h4>- maths</h4></p>
<p><h4>- architecture</h4></p>
<p><h4>- physics, chemistry, biology</h4></p>
<p><h4>- business and economics</h4></p>

{% endblock %}

{% include 'snippets/footer.html' %}

templates/main/stanford.html
{% extends 'base.html' %}
{% load static %}
{% include 'snippets/header.html' %}

{% block content %}
<h1>Stanford University</h1>
<p><h3>Stanford University was founded by former California Governor Leland Stanford in 1891. More than 17,000 students study at Stanford, most of them undergraduates and graduate students.
    The main campus was designed by architect and designer Frederick Law Olmsted, who also designed Central Park and Prospect Park in New York. Now the campus is one of the largest in the United States - there are even 24 bus routes on its territory.
    Currently, 17 Nobel laureates, 4 Pulitzer Prize winners, 288 members of the American Academy of Arts and Sciences and 109 members of the National Academy of Engineering work and teach at the university. The university invests heavily in the development of research activities, and also motivates students to create start-ups, some of which are funded by the university and its trustees.
    The 31st US President Herbert Hoover, the founders of high-tech companies: Sergey Brin (Google), William Hewlett and David Packard (Hewlett-Packard), Reed Hastings (Netflix), Mike Krieger (Instagram) studied at Stanford University at different times; and actress Sigourney Weaver.</h3></p>
<img src="{% static 'img/stanford1.jpg' %}" alt="stanford">
<h2>Why go to the Stanford University?</h2>
<p><h3>- about 650 student communities covering a wide range of interests, including art, culture, media, politics. There are also a lot of academic clubs, for example, robotics, energy and others.</h3></p>
<p><h3>- more than 30 sports teams, including rowing, cycling and cheerleading teams;</h3></p>
<p><h3>- a prestigious diploma that is valued by employers around the world.</h3></p>


<h2>Strong directions:</h2>
<p><h4>- engineering</h4></p>
<p><h4>- information technology and computer science</h4></p>
<p><h4>- natural and exact sciences</h4></p>
<p><h4>- jurisprudence</h4></p>
<p><h4>- political science and international relations</h4></p>


{% endblock %}

{% include 'snippets/footer.html' %}

templates/main/universities.html
{% extends 'base.html' %}
{% load static %}
{% include 'snippets/header.html' %}

{% block content %}
<p align="center"><h2>Universities in the USA</h2></p>
<p><h3>US universities are considered the most prestigious in the world. According to the QS 2020 ranking, 38 of American universities are among the world’s top 150. The front-runners are Massachusetts Institute of Technology, Harvard University, and Stanford University. Largely due to their reputation, an American degree opens up excellent career prospects anywhere in the world. However, when submitting documents, one should take into account that there is no free education in the USA.
    Admission to US universities and colleges is characterized by extremely high competition. Another challenge is taking standardized tests such as SAT / ACT and GRE / GMAT. The selection is also based on the language test results, Grade Point Average, letter of motivation and other application documents.</h3></p>

<a href="{% url 'university:mit' %}" class="nav-item nav-link active"><h1>MIT University</h1></a>
<img src="{% static 'img/mit1.jpg' %}" alt="mit">

<a href="{% url 'university:stanford' %}" class="nav-item nav-link active"><h1>Stanford University</h1></a>
<img src="{% static 'img/stanford.jpg' %}" alt="stanford">

<a href="{% url 'university:harvard' %}" class="nav-item nav-link active"><h1>Harvard University</h1></a>
<img src="{% static 'img/harvard.jpg' %}" alt="harvard">

<a href="{% url 'university:columbia' %}" class="nav-item nav-link active"><h1>Columbia University</h1></a>
<img src="{% static 'img/columbia.jpg' %}" alt="harvard">


{% endblock %}

{% include 'snippets/footer.html' %}

templates/snippets/footer.html
{% load static %}
 <!-- Footer Start -->
<div class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h3 class="title">Useful Links</h3>
                            <ul>
                                <li><a href="{% url 'university:mit' %}">MIT University</a></li>
                                <li><a href="{% url 'university:stanford' %}">Stanford University</a></li>
                                <li><a href="{% url 'university:harvard' %}">Harvard University</a></li>
                                <li><a href="{% url 'university:columbia' %}">Columbia University</a></li>

                            </ul>
                        </div>
                    </div>


                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h3 class="title">Get in Touch</h3>
                            <div class="contact-info">
                                <p><i class="fa fa-map-marker"></i>Bunyodkor, street 7G</p>
                                <p><i class="fa fa-envelope"></i>joraev.azam@gmail.com</p>
                                <p><i class="fa fa-phone"></i>+998993143808</p>
                                <div class="social">
                                    <a href="https://t.me/joraev_a"><i class="fab fa-telegram"></i></a>
                                    <a href="https://instagram.com/joraev_azam?utm_medium=copy_link"><i class="fab fa-instagram"></i></a>
                                    <a href="https://www.youtube.com/channel/UCHNjoEcp7OcU1y8wANhSduw"><i class="fab fa-youtube"></i></a>
                                </div>


                            </div>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h3 class="title">Scan me</h3>
                            <div class="newsletter">
                                <p>Scan Qr-Code to get more information</p>
                                <p>On the next page you can get more information about education of other countries.</p>

                            </div>
                        </div>
                    </div>
                    <img src="{% static 'img/qr-code (4).png' %}" alt="qr-code">
                </div>
            </div>
        </div>
<!-- Footer End -->


<!-- Footer Bottom Start -->
<!--<div class="footer-bottom">-->
<!--            <div class="container">-->
<!--                <div class="row">-->
<!--                    <div class="col-md-6 copyright">-->
<!--                        <p><a href="https://www.unipage.net/ru/universities_usa">World Education&copy; </a></p>-->
<!--                    </div>-->

<!--                    &lt;!&ndash;/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/&ndash;&gt;-->
<!--                    <div class="col-md-6 template-by">-->
<!--                        <p><a href="https://www.unipage.net/ru/universities_usa">World Education&copy; </a></p>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!-- Footer Bottom End -->


<!-- Back to Top -->
<a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

templates/snippets/header.html
{% load static %}
 <!-- Top Header Start -->
<div class="top-header">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-3 col-md-4">
                        <div class="logo">
                            <a href="">
                                <img src="{% static 'img/3_29_2022 10_29_53 AM.png' %}" alt="Logo">
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-4">
                        <div class="search">
                            <input type="text" placeholder="Search">
                            <button><i class="fa fa-search"></i></button>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-4">
                        <div class="social">
                             <a href="https://t.me/joraev_a"><i class="fab fa-telegram"></i></a>
                             <a href="https://instagram.com/joraev_azam?utm_medium=copy_link"><i class="fab fa-instagram"></i></a>
                             <a href="https://www.youtube.com/channel/UCHNjoEcp7OcU1y8wANhSduw"><i class="fab fa-youtube"></i></a>
                             <a href=""><i class="fab fa-twitter"></i></a>
                             <a href=""><i class="fab fa-facebook"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
<!-- Top Header End -->


<!-- Header Start -->
<div class="header">
            <div class="container">
                <nav class="navbar navbar-expand-md bg-dark navbar-dark">
                    <a href="#" class="navbar-brand">MENU</a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav m-auto">
                            <a href="{% url 'university:universities' %}" class="nav-item nav-link">Home</a>
                            <a href="{% url 'university:list-universities' %}" class="nav-item nav-link">Universities</a>
                            <a href="{% url 'university:education' %}" class="nav-item nav-link">Education</a>
                            <a href="{% url 'university:add-page' %}" class="nav-item nav-link">Add University</a>
                            <a href="{% url 'university:news-list' %}" class="nav-item nav-link">added</a>
                            <a href="contact.html" class="nav-item nav-link">Contact Us</a>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
<!-- Header End -->

university/templates/add-news.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class='post-entry'>
        <form action="" method="post">{% csrf_token  %}
            {{ form.as_p }}
            <input type="submit" value="Save" />
        </form>
    </div>
{% endblock %}

university/templates/all_news.html
{% extends 'base.html' %}
{% load static %}
{% include 'snippets/header.html' %}

{% block content %}
        {% for post in news_list %}
            <div class='post-entry' >
                <h3>{{ post.name }}</h3>
                <h6>{{ post.country }}</h6>
            </div>
        {% endfor %}
{% endblock %}

{% include 'snippets/footer.html' %}

university/templates/delete_news.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class='post-entry'>
        <h2>Delete News</h2>
        <form action="" method="post">{% csrf_token %}
            <p>Are you sure to delete "{{ new.name }}" ?</p>
            <input type="submit" value="Confirm" />
        </form>
    </div>
{% endblock %}

university/templates/detail-page.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class='post-entry' >
        <h1>{{ news.name }}</h1>
        <img src="{{ news.image.url }}"/>
        <h3>{{ news.about }}</h3>
        <h5>{{ news.country }}</h5>

        <p><a href="{% url 'university:update' news.pk %}">Edit</a></p>
        <p><a href="{% url 'university:delete' news.pk %}">Delete</a></p>
        <p><a href="{% url 'university:home' %}">Home</a></p>

    </div>
{% endblock %}

university/templates/news.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="top-news">
    <div class="container-fluid">
        <div class="row">
            {% for post in object_list %}
            <div class='post-entry' ></div>
            <div class="col-md-6">
                <div class="tn-img">
                    <img src="{{ post.imageUrl }}"/>
                    <div class="tn-content">
                        <div class="tn-content-inner">
                            <a class="tn-date" href=""><i class="far fa-clock"></i>{{ post.author }}</a>
                            <a class="tn-title" href="{% url 'university:detail-page' post.id %}">{{ post.name }}</a>
                            <a class="tn-title" href="">{{ post.country }}</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
{% endblock %}

university/templates/update_news.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class='post-entry' >
    <h>Edit News</h>
        <form action="" method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Update" />

        </form>
    </div>
{% endblock %}